#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

require __DIR__ . '/config/dotenv.php';
$dependencyFactory = require __DIR__ . '/config/migration.php';

use Doctrine\Migrations\Tools\Console\Command;
use Symfony\Component\Console\Application;

$cli = new Application('Doctrine Migrations');
$cli->setCatchExceptions(true);

$cli->addCommands(array(
    new Command\DumpSchemaCommand($dependencyFactory),
    new Command\ExecuteCommand($dependencyFactory),
    new Command\GenerateCommand($dependencyFactory),
    new Command\LatestCommand($dependencyFactory),
    new Command\ListCommand($dependencyFactory),
    new Command\MigrateCommand($dependencyFactory),
    new Command\RollupCommand($dependencyFactory),
    new Command\StatusCommand($dependencyFactory),
    new Command\SyncMetadataCommand($dependencyFactory),
    new Command\VersionCommand($dependencyFactory),
));

$cli->run();